language: go

go:
  - "1.12.6"

services: 
  - docker

install:
  - make image-dev #build

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password -stdin
  - make push-dev #push
