dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t gocrawler .
        - docker images
        - docker tag gocrawler $DOCKER_USERNAME/gocrawler
        - docker push $DOCKER_USERNAME/gocrawler
